# Generated by Django 4.2 on 2023-05-12 12:11

import django.core.validators
from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_film_poster_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('plot', models.TextField(blank=True, null=True, verbose_name='Plot')),
                ('release_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY\x02MM-DD</em>.', null=True, verbose_name='Release date')),
                ('runtime', models.IntegerField(blank=True, help_text='Please enter an integer value (minutes)', null=True, verbose_name='Runtime')),
                ('rate', models.FloatField(default=5.0, help_text='Please enter an float value (range 1.0 - 10.0)', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rate')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=myapp.models.poster_path, verbose_name='Poster')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a serial genre (e.g. sci-fi, comedy)', max_length=50, unique=True, verbose_name='Genre name'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.AddField(
            model_name='serial',
            name='genres',
            field=models.ManyToManyField(help_text='Select a genre for this serial', to='myapp.genre'),
        ),
    ]
