# Generated by Django 4.2 on 2023-05-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_country_delete_genre_alter_serial_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Countries',
        ),
    ]
