# Generated by Django 4.2 on 2023-05-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_country_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Countrie',
        ),
    ]
