# Generated by Django 4.2 on 2023-05-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_countries_countrie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serial',
            new_name='Tank',
        ),
    ]
