# Generated by Django 4.2 on 2023-05-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_serial_tank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
