# Generated by Django 4.2 on 2023-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='genres',
            field=models.ManyToManyField(help_text='Select a genre for this tank', to='myapp.countrie'),
        ),
    ]
