# Generated by Django 4.2 on 2023-05-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_stroj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stroj',
            new_name='Machine',
        ),
    ]
