# Generated by Django 4.2 on 2023-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_companie_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='companie',
            name='name',
            field=models.CharField(help_text='Enter a company name', max_length=50, unique=True, verbose_name='Company'),
        ),
    ]
