# Generated by Django 4.2 on 2023-05-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_companie_info_alter_companie_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companie',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
    ]
