# Generated by Django 4.2 on 2023-05-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_companie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tank',
        ),
    ]
