# Generated by Django 4.2 on 2023-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a specific tank name', max_length=200, verbose_name='Tank')),
                ('max_speed', models.IntegerField(blank=True, help_text='Please enter an integer value (km/h)', null=True, verbose_name='Maximal speed')),
                ('weight', models.IntegerField(blank=True, help_text='Please enter an integer value (tons)', null=True, verbose_name='Weight')),
                ('penetration', models.IntegerField(blank=True, help_text='Please enter an integer value (millimeters)', null=True, verbose_name='Penetration')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
