# Generated by Django 4.2 on 2023-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a crewman name', max_length=50, unique=True, verbose_name='Crews')),
                ('surname', models.CharField(help_text='Enter a crewman surname', max_length=50, unique=True, verbose_name='Crews')),
                ('birth_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY\x02MM-DD</em>.', null=True, verbose_name='Date of birth')),
                ('tank_type', models.CharField(blank=True, choices=[('driver', 'Driver'), ('commander', 'Commander'), ('gunner', 'Gunner'), ('loader', 'Loader')], help_text='Select crewman role', max_length=10, verbose_name='Tank role')),
            ],
            options={
                'ordering': ['-birth_date', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='tank',
            name='tank_type',
            field=models.CharField(blank=True, choices=[('light tank', 'Light tank'), ('medium tank', 'Medium tank'), ('heavy tank', 'Heavy tank'), ('tank destroyer', 'Tank destroyer'), ('anti air tank', 'Anti air tank')], help_text='Select tank type', max_length=15, verbose_name='Tank type'),
        ),
    ]
