# Generated by Django 4.2 on 2023-05-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_crew_alter_tank_tank_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
    ]
