# Generated by Django 4.2 on 2023-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_delete_crew_delete_machine_delete_tank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a crewman name', max_length=50, verbose_name='Name')),
                ('surname', models.CharField(help_text='Enter a crewman surname', max_length=50, unique=True, verbose_name='Surname')),
                ('birth_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY\x02MM-DD</em>.', null=True, verbose_name='Date of birth')),
                ('tank_type', models.CharField(blank=True, choices=[('driver', 'Driver'), ('commander', 'Commander'), ('gunner', 'Gunner'), ('loader', 'Loader')], help_text='Select crewman role', max_length=10, verbose_name='Tank role')),
            ],
            options={
                'ordering': ['-birth_date', 'name'],
            },
        ),
    ]
