# Generated by Django 4.2 on 2023-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='crew',
        ),
        migrations.AlterField(
            model_name='tank',
            name='creation_date',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>DD.MM.YYYY</em>.', null=True, verbose_name='First tank made'),
        ),
        migrations.AddField(
            model_name='machine',
            name='crew',
            field=models.ManyToManyField(help_text='Select a tankcrew for this tank', to='myapp.crew'),
        ),
    ]
