# Generated by Django 4.2 on 2023-05-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_machine_crew_alter_tank_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='country',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
    ]
